/* 
 * Swagger Иди нахер
 *
 * This is a sample server Petstore server.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters.
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Defines LessonType
    /// </summary>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum LessonType
    {
        
        /// <summary>
        /// Enum Practic for value: practic
        /// </summary>
        [EnumMember(Value = "practic")]
        Practic = 1,
        
        /// <summary>
        /// Enum Lecture for value: lecture
        /// </summary>
        [EnumMember(Value = "lecture")]
        Lecture = 2,
        
        /// <summary>
        /// Enum Lab for value: lab
        /// </summary>
        [EnumMember(Value = "lab")]
        Lab = 3
    }

}
